// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/config.ts";
import * as $1 from "./routes/api/export/gallery/zip/[gid].ts";
import * as $2 from "./routes/api/task/list.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Container.tsx";
import * as $$1 from "./islands/Settings.tsx";

const manifest = {
    routes: {
        "./routes/api/config.ts": $0,
        "./routes/api/export/gallery/zip/[gid].ts": $1,
        "./routes/api/task/list.ts": $2,
        "./routes/index.tsx": $3,
    },
    islands: {
        "./islands/Container.tsx": $$0,
        "./islands/Settings.tsx": $$1,
    },
    baseUrl: import.meta.url,
    config,
};

export default manifest;
