name: Docker image deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/deno.yml'
      - api.yml
      - docker-compose.yml
      - '**.md'
  workflow_dispatch:

concurrency:
  group: docker
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: lifegpc
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lifegpc/eh_downloader_base
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Switch docker drive
        run: docker buildx create --use
      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=docker-cache
          cache-to: type=gha,mode=max,scope=docker-cache
          build-args: |
            DENO_DEPLOYMENT_ID=${{ github.sha }}
